version: '2'
services:
  overheardes-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/overheardes/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=overheardes
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
